<?php
/**
 * Created by Karina Hinkelthein
 * 07.02.2015
 */

$isHomePage = isset($isHomePage) ? $isHomePage : false;
$headline = isset($headline) ? $headline : false;
?>

<header>
    <?php echo getPageHeadline($isHomePage, $headline); ?>

<!--    <nav>-->
<!--        <ol class="cf">-->
<!--            <li><a href="#what-is-this-place">What is this place?</a></li>-->
<!--            <li><a href="#accessible-modal-window">Accessible modal window</a></li>-->
<!--            <li><a href="#drag-and-drop">A little bit of Drag & Drop</a></li>-->
<!--            <li><a href="#inspiration">Inspiration</a></li>-->
<!--        </ol>-->
<!--    </nav>-->
</header>